# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3055232a7e01fc0a657f1a2a251dc4d63756926d8b5c150ad2573b6d9dca025e2d2aa131e6244d96752a91957d133c12bbaafc95732e88107d90bcb4d950dd52

test:
  secret_key_base: 4060b1b81728b605aadfef367d2572c46b9483cd1c00e40223868272198cc78374c2e425802d1c03a10a673fedd709338d7d8d4e6ae27de2d25bcdae56f0d867

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
